var NewCandidateForm = $.Class.create({
	initialize: function() {
		this.template = '<div id="newCandidate" class="profile-panel">'
			+'<div class="profile-fieldset-title">Personal Info</div>'
			+ '<div class="profile-panel-body">'
				+ '<div class="profile-field">'
					+ '<div class="profile-form-label">'
						+ '<span>Name</span>'
					+ '</div>'
					+ '<div class="profile-form-field-container">'
						+ '<input type="text" id="newCandidateName" ></input>'
					+ '</div>'
				+ '</div>'
				+ '<div class="profile-field">'
					+ '<div class="profile-form-label">'
						+ '<span>Gender</span>'
					+ '</div>'
					+ '<div class="profile-form-field-container">'
						+ '<span></span>'
					+ '</div>'
				+ '</div>'
				+ '<div class="profile-field">'
					+ '<div class="profile-form-label">'
						+ '<span>College</span>'
					+ '</div>'
					+ '<div class="profile-form-field-container">'
						+ '<span></span>'
					+ '</div>'
				+ '</div>'
				+ '<div class="profile-field">'
					+ '<div class="profile-form-label">'
						+ '<span>Logic</span>'
					+ '</div>'
					+ '<div class="profile-form-field-container">'
						+ '<span></span>'
					+ '</div>'
				+ '</div>'
				+ '<div class="profile-field">'
					+ '<div class="profile-form-label">'
						+ '<span>Wonderlic</span>'
					+ '</div>'
					+ '<div class="profile-form-field-container">'
						+ '<span></span>'
					+ '</div>'
				+ '</div>'
				+ '<div class="profile-field">'
					+ '<div class="profile-form-label">'
						+ '<span>Comments</span>'
					+ '</div>'
					+ '<div class="profile-form-field-container">'
						+ '<textarea id="newCandidateComments"></textarea>'
					+ '</div>'
				+ '</div>'
			+ '</div>'
		+ '</div>';
	},
	render:function() {
		var newCandidateContainer = $('#newCandidateContainer');
		newCandidateContainer.children().remove();
		newCandidateContainer.append($(this.template));
	}
	
});